Repository collectd/collectd, pull requests merged in 2018-08, with the labels that each got.

#2904 redis plugin: Added option for connecting via UNIX socket
  src/collectd.conf.in
  src/collectd.conf.pod
  src/redis.c
Labels: Automerge, Feature

#2907 Fix warning that pkgdatadir and pkglibdir were previously defined.
  Makefile.am
Labels: Bug, Pending feedback, build

#2864 Add --with-libxml2 option to configure.
  configure.ac
Labels: Pending feedback, build

#2916 nfs: Fix number of fields for NFSv4
  src/nfs.c
Labels: Automerge
