Repository collectd/collectd, pull requests merged in 2018-05, with the labels that each got.

#2760 docs: Fix typo in collectd.conf.pod
  src/collectd.conf.pod
Labels: Automerge, documentation

#2767 netlink plugin: Handle new counter from Linux kernel version 4.6+.
  configure.ac
  src/netlink.c
  src/types.db
Labels: Feature, Pending feedback, linux only

#2779 Remove empty `cmd_listval_t` data structure and related no-op code.
  src/utils_cmd_listval.c
  src/utils_cmd_listval.h
  src/utils_cmds.c
  src/utils_cmds.h
Labels: Automerge, Cleanup

#2784 Added missing include of 'kstat.h'
  src/daemon/common.c
Labels: Automerge, Bug, build, solaris only

#2787 Added missing include of 'config.h'
  src/libcollectdclient/collectd/network_buffer.h
Labels: Automerge, Bug, build, solaris only

#2788 Cherry-picked #2717 and #2741 to collectd-5.8
  src/libcollectdclient/network_parse.c
  src/stdendian.h
Labels: Automerge, Bug, build, solaris only

#2792 Added missing include of 'config.h' and cherry-picked #2761 for AIX support in collectd-5.8.
  src/stdendian.h
  src/utils_config_cores_test.c
Labels: Automerge, Bug, aix only, build, solaris only

#2793 Cherry-picked aadf9ba and 45df07a to collectd-5.8
  Makefile.am
  src/daemon/common.h
  src/libcollectdclient/collectd/stdendian.h
  src/libcollectdclient/network_parse.c
Labels: Automerge, Bug, build, macos only, solaris only

#2789 redis: [impr/fix] ability to select db for queries
  src/collectd.conf.in
  src/collectd.conf.pod
  src/redis.c
Labels: Feature
