Repository collectd/collectd, pull requests merged in 2018-07, with the labels that each got.

#2845 redis plugin: Remove `operations_per_second` metric.
  src/redis.c
Labels: Pending feedback

#2847 tree-wide: Use interval value from plugin context, do not set 'vl->interval' in plugins more.
  src/collectd.conf.pod
  src/curl.c
  src/curl_json.c
  src/curl_xml.c
  src/daemon/configfile.c
  src/daemon/plugin.c
  src/dbi.c
  src/modbus.c
  src/oracle.c
  src/postgresql.c
  src/snmp.c
  src/tail.c
  src/tail_csv.c
  src/utils_db_query.c
  src/utils_db_query.h
  src/utils_tail_match.c
  src/utils_tail_match.h
Labels: Bug, Cleanup, Pending feedback, core

#2631 Graphite 1.1+ tag support
  src/collectd.conf.pod
  src/utils_format_graphite.c
  src/utils_format_graphite.h
  src/utils_format_graphite_test.c
  src/write_graphite.c
  src/write_kafka.c
Labels: Feature, Pending contributor action

#2733 New plugin to read PCIe errors
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/pcie_errors.c
  src/pcie_errors_test.c
  src/testing.h
Labels: New plugin

#2850 write_prometheus: Added MHD_USE_INTERNAL_POLLING_THREAD flag
  src/write_prometheus.c
Labels: Automerge

#2851 routeros: Add support for temperature and voltage data
  src/collectd.conf.in
  src/collectd.conf.pod
  src/routeros.c
Labels: Feature
