Repository collectd/collectd, pull requests merged in 2018-10, with the labels that each got.

#2938 src/utils_format_json.c: Remove chatty debug messages.
  src/utils_format_json.c
Labels: Automerge, Cleanup

#2937 exec plugin: dynamically allocate grname buffer for getgrnam_r
  src/exec.c
Labels: Automerge, Bug

#2941 Backport: ceph plugin: fix scan-build warnings
  src/ceph.c
Labels: Automerge, Bug

#2942 ntpd: plug potential leak on error
  src/ntpd.c
Labels: Automerge, Bug

#2944 src/daemon/common.h: Fix typo.
  src/daemon/common.h
Labels: Automerge, Cleanup

#2945 .travis.yml: Determine number of CPUs at runtime.
  .travis.yml
Labels: Automerge, build

#2948 turbostat plugin: free the right variable
  src/turbostat.c
Labels: Automerge, Bug

#2949 Fix detection of xmmsctrl.h
  configure.ac
Labels: Automerge, build

#2952 disk plugin: Support Linux kernels with additional fields.
  src/disk.c
Labels: Automerge, Bug, linux only

#2950 wireless plugin: Add bitrate metric.
  src/wireless.c
Labels: Automerge, Feature, linux only

#2953 ntpd: plug potential leak on error
  src/ntpd.c
Labels: Automerge, Bug

#2955 disk plugin: Drop support for Linux 2.4.
  src/disk.c
Labels: Automerge, Cleanup, linux only

#2957 virt plugin: Fix typo in error messages.
  src/virt.c
Labels: Automerge, Cleanup

#2959 Merge collectd-5.7 into collectd-5.8
  src/disk.c
  src/powerdns.c
Labels: Automerge

#2806 turbostat plugin: New metrics: P-states,Turboboost,Platform TDP,Uncore bus ratio
  src/msr-index.h
  src/turbostat.c
  src/types.db
Labels: Feature

#2963 ovs_stats: add macro to populate counters list
  src/ovs_stats.c
Labels: Cleanup

#2968 change HAVE_UDEV_H to HAVE_LIBUDEV_H for bug 2651
  src/disk.c
Labels: Bug, build

#2970 src/utils_oauth.c: Renew OAuth tokens 30 seconds before they expire.
  src/utils_oauth.c
Labels: Bug

#2972 virt plugin: Remove optional virDomainGetCPUStats() from main flow
  src/virt.c
Labels: Bug

#2923 New plugin: gpu_nvml collects NVIDIA GPU stats.
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/gpu_nvidia.c
Labels: New plugin

#2978 virt plugin: Cleanup
  src/virt.c
Labels: Automerge, Cleanup

#2979 swap plugin: Drop support for Linux 2.4.
  src/swap.c
Labels: Cleanup

#2551 disk: in linux, reset the disk when it disappear from /proc/diskstats
  src/disk.c
Labels: Bug, linux only
