Repository collectd/collectd, pull requests merged in 2018-09, with the labels that each got.

#2913 Add support for humidity in sensors plugin
  src/sensors.c
Labels: Feature, Pending contributor action

#2917 fix c_avl_iterator_prev
  src/daemon/utils_avltree.c
  src/daemon/utils_avltree_test.c
Labels: Bug

#2919 Fix segfault in libvirt plugin
  src/virt.c
Labels: Bug

#2922 contrib/docker/rootfs_prefix: Add MIT license header.
  contrib/docker/rootfs_prefix/rootfs_prefix.c
Labels: Cleanup
