Repository collectd/collectd, pull requests merged in 2018-11, with the labels that each got.

#2976 Add a new UNKNOWN state as the initial state of metrics
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
  src/threshold.c
  src/write_riemann_threshold.c
Labels: core

#2988 log_logstash plugin: Fix non-portable struct initialization with "{}".
  src/log_logstash.c
Labels: Cleanup

#2994 collectd.conf(5): Improve the tail plugin's documentation.
  src/collectd.conf.pod
Labels: documentation
