Repository collectd/collectd, pull requests merged in 2018-06, with the labels that each got.

#2813 config parser: Improved error reporting on global options
  src/daemon/configfile.c
Labels: Automerge, core

#2817 snmp plugin: Implemented new configuration options
  src/collectd-snmp.pod
  src/collectd.conf.in
  src/snmp.c
Labels: Feature, Pending feedback

#2822 ntpd: Don't treat normal peers as refclocks.
  src/ntpd.c
Labels: Automerge, Bug

#2825 rrdtool plugin: Added more error reporting
  src/daemon/common.c
  src/rrdtool.c
Labels: Automerge

#2819 snmp plugin: HostOID and FilterOID options
  Makefile.am
  src/collectd-snmp.pod
  src/collectd.conf.in
  src/snmp.c
Labels: Bug, Feature, Pending feedback

#2826 redis plugin: Bugfixes, extended error reporting, persistent connections and parallel polling
  src/collectd.conf.pod
  src/redis.c
  src/types.db
  src/write_redis.c
Labels: Automerge, Bug, Feature

#2821 RFE: Add plugin name field into plugin context use it to improve error reporting
  src/bind.c
  src/daemon/common.c
  src/daemon/configfile.c
  src/daemon/plugin.c
  src/daemon/plugin.h
  src/daemon/plugin_mock.c
Labels: Cleanup, Pending feedback, core

#2833 cleanup: cf_util_get* instead of local copy in plugins, prefixed error reporting
  src/filecount.c
  src/gmond.c
  src/memcachec.c
  src/netapp.c
  src/table.c
  src/threshold.c
  src/utils_db_query.c
  src/utils_format_graphite.c
  src/utils_rrdcreate.c
  src/write_riemann.c
  src/write_sensu.c
Labels: Automerge, Cleanup

#2831 network plugin: Add BindAddress option
  src/collectd.conf.pod
  src/network.c
Labels: Feature, Pending contributor action

#2838 redis plugin: Report keyspace hitratio
  src/redis.c
Labels: Automerge, Feature
