Repository collectd/collectd, pull requests merged in 2019-06, with the labels that each got.

#3167 Makefile.am: Remove a needless tab
  Makefile.am
Labels: Unlisted Change

#3175 redhat spec: fix build due to new upstream plugins
  contrib/redhat/collectd.spec
Labels: Unlisted Change

#3182 Fix return value or loglevel for several plugins
  src/barometer.c
  src/daemon/configfile.c
  src/load.c
  src/logfile.c
  src/openvpn.c
  src/syslog.c
  src/ted.c
Labels: Automerge, Bug

#3156 dns plugin: Do not use headers from glibc
  configure.ac
  src/utils/dns/dns.c
  src/utils/dns/dns.h
Labels: Bug

#3193 Add standard include early or _FILE_OFFSET_BITS will have definition …
  src/daemon/globals.c
  src/utils/cmds/cmds_test.c
  src/utils/common/common_test.c
  src/utils/proc_pids/proc_pids_test.c
Labels: Automerge, Bug, Unlisted Change

#3178 regex match: Fix unexpected match with empty meta data
  src/match_regex.c
Labels: Bug
