Repository collectd/collectd, pull requests merged in 2019-02, with the labels that each got.

#3054 CONTRIBUTING.md: Document the new change log requirement / behavior.
  CONTRIBUTING.md
Labels: Unlisted Change, documentation

#3053 CODEOWNERS: Add code owners as discussed at the meetup.
  CODEOWNERS
Labels: core

#3059 write_prometheus plugin: Only use SOCK_CLOEXEC if it is defined.
  src/write_prometheus.c
Labels: Automerge, Bug

#3057 collection3: Add Type for smart_temperature
  contrib/collection3/etc/collection.conf
Labels: Feature, Unlisted Change

#3058 collection3: Output graph.cgi debug as UTF-8
  contrib/collection3/bin/graph.cgi
Labels: Automerge, Feature, Unlisted Change

#3063 strjoin(): Fix behavior if output buffer is NULL.
  src/daemon/common.c
  src/daemon/common_test.c
Labels: Automerge, Bug, core

#3066 Merge collectd-5.8 into master
  src/collectd.conf.pod
  src/daemon/common.c
  src/daemon/common_test.c
  src/log_logstash.c
  src/sensors.c
  src/write_prometheus.c
Labels: Unlisted Change

#3021 Libcollectdclient fix stringop warning
  src/libcollectdclient/network_parse.c
Labels: Bug

#3055 Add OS X to the Travis build matrix.
  .travis.yml
Labels: Unlisted Change

#3061 CONTRIBUTING.md: Improve wording around ChangeLog; fix example.
  docs/CONTRIBUTING.md
Labels: Automerge, Unlisted Change, documentation

#3070 Travis improvements
  .travis.yml
Labels: Unlisted Change

#3078 Document the snmp plugin's use of complex reads
  src/collectd-snmp.pod
Labels: documentation

#3086 Reduce the amount of output from ./configure
  configure.ac
Labels: Unlisted Change

#3093 Sensu fix warning
  src/write_sensu.c
Labels: Unlisted Change

#3092 Don't hide errors when creating manpage
  Makefile.am
Labels: Unlisted Change

#3074 Re-implement CI using cirrus-ci
  .cirrus.yml
Labels: Unlisted Change, build

#3090 lua plugin: cleanup properly when shutting down
  src/lua.c
Labels: Automerge, Bug

#3060 contrib/docker/: Switch to Debian slim, separate ENTRYPOINT/CMD, install suggestions.
  contrib/docker/50docker-apt-conf
  contrib/docker/Dockerfile
Labels: Unlisted Change

#3065 changed time format to no longer lose microseconds
  src/rrdcached.c
Labels: Automerge, Feature

#3095 Build system: enable the "df" plugin when getmntent_r() is available.
  configure.ac
Labels: build

#3096 pod2man: remove --errors argument
  Makefile.am
Labels: Unlisted Change

#3097 configure.ac: Fix include of "utils/mount/mount.h".
  configure.ac
  src/utils/mount/mount.h
Labels: Automerge, Unlisted Change, build

#3098 ovs_stats plugin: fix compiler warning
  src/ovs_stats.c
Labels: Unlisted Change

#3099 turbostat plugin: fix two compiler warnings
  src/turbostat.c
Labels: Unlisted Change

#3100 virt plugin: fix compiler warning
  src/virt.c
Labels: Unlisted Change

#3103 write_prometheus plugin: fix compiler warning
  src/write_prometheus.c
Labels: Unlisted Change

#3102 oauth.c: fix compiler warning
  src/utils/oauth/oauth.c
Labels: Unlisted Change

#3104 intel_rdt plugin: fix compiler warnings
  src/intel_rdt.c
Labels: Unlisted Change

#3110 configure.ac: keep the list of plugins sorted
  configure.ac
Labels: Unlisted Change
