Repository collectd/collectd, pull requests merged in 2019-04, with the labels that each got.

#3116 virt plugin: Fix segfaults on shutdown
  src/virt.c
Labels: Bug

#2891 Intel RDT plugin: add support for groups of PIDs.
  Makefile.am
  src/collectd.conf.in
  src/collectd.conf.pod
  src/intel_rdt.c
  src/intel_rdt_test.c
  src/utils/proc_pids/proc_pids.c
  src/utils/proc_pids/proc_pids.h
  src/utils/proc_pids/proc_pids_test.c
Labels: Feature

#3136 Remove ProtectSystem from service file
  contrib/systemd.collectd.service
Labels: Unlisted Change

#3001 write_graphite plugin: Add option to reverse host
  src/collectd.conf.in
  src/collectd.conf.pod
  src/utils/format_graphite/format_graphite.c
  src/utils/format_graphite/format_graphite.h
  src/write_graphite.c
Labels: Feature
