Repository collectd/collectd, pull requests merged in 2019-05, with the labels that each got.

#3144 lua plugin: Make it possible to register more than one reader/writer; bugfixes; cleanup.
  src/collectd-lua.pod
  src/lua.c
Labels: Bug

#3019 Add write_syslog output plugin
  AUTHORS
  ChangeLog
  Makefile.am
  README
  configure.ac
  contrib/redhat/collectd.spec
  src/collectd.conf.in
  src/collectd.conf.pod
  src/write_syslog.c
Labels: New plugin

#3149 virt plugin: Do not fail if no connection on init()
  src/virt.c
Labels: Bug

#3148 virt plugin: Updates regarding to 'domain_state' metric
  src/collectd.conf.pod
  src/virt.c
Labels: Bug

#3152 virt plugin: Fix typo after #3151
  src/virt.c
Labels: Unlisted Change

#2986 curl plugin: add AddressFamily
  src/collectd.conf.in
  src/collectd.conf.pod
  src/curl.c
  src/curl_json.c
  src/curl_xml.c
Labels: Feature

#3158 Copy MetaData to Riemann events in write_riemann
  src/write_riemann.c
Labels: Feature, Pending feedback
