Repository collectd/collectd, pull requests merged in 2019-07, with the labels that each got.

#2725 utils_cache: fix pointer reference and meta_data ingestion
  src/daemon/utils_cache.c
Labels: Unlisted Change

#3203 Add missing definitions for libnetsnmpagent
  configure.ac
Labels: Automerge

#3205 powerdns: Added 'unreachables' reporting
  src/powerdns.c
Labels: Automerge

#3206 Move Makefile rules for pid_test inside conditional for code
  Makefile.am
Labels: Automerge, build

#3072 Add a unit test for the network plugin.
  Makefile.am
  src/daemon/plugin_mock.c
  src/network_test.c
Labels: Feature

#3224 Move trusted-contributors down the list
  CODEOWNERS
Labels: Unlisted Change

#3217 daemon: Check if plugin actually loaded before reporting configuration issues
  src/daemon/configfile.c
  src/daemon/plugin.c
  src/daemon/plugin.h
  src/daemon/plugin_mock.c
Labels: core

#3207 Fix bug that leads to CPPFLAGS gets overridden with CFLAGS when libxm…
  configure.ac
  src/network.c
Labels: Automerge, Unlisted Change

#3229 Cppflags backport
  configure.ac
  src/network.c
Labels: Automerge, Unlisted Change
