Repository collectd/collectd, pull requests merged in 2019-10, with the labels that each got.

#3290 Add changelog to prepare 5.9.2 release
  ChangeLog
Labels: Automerge, Unlisted Change

#3299 Merge stable branch back to master
  ChangeLog
  src/utils/common/common.c
  version-gen.sh
Labels: Unlisted Change

#3308 Travis improvements for MacOS
  .travis.yml
Labels: Unlisted Change

#3307 Travis: switch to Bionic
  .travis.yml
Labels: Unlisted Change

#3316 Merge make check fixes from collectd 5.8 to 5.9
  src/utils/common/common_test.c
Labels: Unlisted Change

#3317 Merge check fixes from 5.9 branch to master
  src/utils/common/common_test.c
Labels: Unlisted Change

#3138 exec: fix a race condition when setting environment variables
  configure.ac
  src/exec.c
Labels: Automerge, Bug

#3318 Changelog and preparation for collectd 5.10
  ChangeLog
  contrib/redhat/collectd.spec
  version-gen.sh
Labels: Unlisted Change

#3323 gpu_nvidia plugin: fix build
  Makefile.am
Labels: Unlisted Change

#3325 configure.ac: fix protobuf/util/time_util.h detection
  configure.ac
Labels: Unlisted Change

#3328 Fix libupsclient detection
  configure.ac
Labels: Unlisted Change
