Repository collectd/collectd, pull requests merged in 2020-08, with the labels that each got.

#3519 [Interns] Add a skeleton for benchmarking distribution_t.
  Makefile.am
  configure.ac
  distbench/Makefile.am
  distbench/bkjg.c
  distbench/function.h
  distbench/main.c
  distbench/margalit.c
  distbench/run-all.sh
  distbench/sshmidt.c
Labels: Interns

#3520 docs/CONTRIBUTING.md: Rename "master" to "main".
  docs/CONTRIBUTING.md
Labels: Unlisted Change, documentation

#3522 Create a benchmark for the distribution
  distbench/Makefile.am
  distbench/bkjg.c
  distbench/bkjg.csv
  distbench/distribution.h
  distbench/function.h
  distbench/main.c
  distbench/margalit.c
  distbench/margalit.csv
  distbench/run-all.sh
  distbench/sshmidt.c
  distbench/sshmidt.csv
Labels: Interns

#2470 Add client interface for the jolokia.org JMX client.
  contrib/curl_jolokia/curl_jolokia.conf
  contrib/curl_jolokia/jolokia_2_collectdcfg.py
  src/collectd.conf.in
  src/collectd.conf.pod
  src/curl_jolokia.c
Labels: New plugin

#3529 Add squares
  src/daemon/distribution.c
  src/daemon/distribution.h
  src/daemon/distribution_test.c
  src/daemon/metric_test.c
Labels: Interns

#3531 Add support for the distribution metrics to the collectd core
  Makefile.am
  src/daemon/distribution.c
  src/daemon/distribution.h
  src/daemon/metric.h
  src/daemon/plugin.h
  src/daemon/plugin_mock.c
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
  src/daemon/utils_cache_test.c
Labels: Interns

#3545 Extended format_json.c to map distribution metrics to json output.
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/metric_test.c
  src/utils/format_json/format_json.c
  src/utils/format_json/format_json_test.c
Labels: Interns

#3549 Makefile.am: Remove undefined symbol "BUILD_WITH_INFINIBAND_LIBS".
  Makefile.am
Labels: Unlisted Change
