Repository collectd/collectd, pull requests merged in 2020-05, with the labels that each got.

#3449 Zookeeper - Fix missing Mntr fields
  src/zookeeper.c
Labels: Bug

#3443 collectd.conf(5): Document the format expected by "sensors"' ignore list.
  src/collectd.conf.pod
Labels: documentation

#3459 ceph plugin: Initialize file descriptor to -1.
  src/ceph.c
Labels: Bug

#3458 types.db(5): Improve wording and document conventions.
  src/types.db.pod
Labels: documentation

#3461 merge collectd 5.10 into collectd-5.11 branch
  src/ceph.c
  src/zookeeper.c
Labels: Unlisted Change
