Repository collectd/collectd, pull requests merged in 2020-03, with the labels that each got.

#3243 Changelog: processes plugin: fix number of running processes
  src/processes.c
Labels: Waiting for response - 1st time

#3037 Add slurm plugin
  AUTHORS
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/slurm.c
  src/types.db
Labels: New plugin

#3375 CODEOWNERS: Add "core maintainers" owning daemon and important plugins.
  CODEOWNERS
Labels: Unlisted Change, core

#3401 Add Code of Conduct.
  CODE_OF_CONDUCT.md
Labels: core

#3415 Remove trailing whitespace in collectd.conf
  src/collectd.conf.in
Labels: Unlisted Change

#3416 collectd.conf.pod: remove trailing whitespaces
  src/collectd.conf.pod
Labels: Unlisted Change

#3408 Merge 5.10 branch into 5.11
  .travis.yml
  ChangeLog
  contrib/redhat/collectd.spec
  src/collectd.conf.pod
  version-gen.sh
Labels: Unlisted Change

#3417 Merge 5.11 into master
  .travis.yml
  ChangeLog
  configure.ac
  contrib/redhat/collectd.spec
  src/collectd.conf.in
  src/collectd.conf.pod
  src/varnish.c
  version-gen.sh
Labels: Unlisted Change

#3413 Remove duplicate plugin author from AUTHORS
  AUTHORS
Labels: Unlisted Change

#3421 Prepare collectd-5.11 release
  AUTHORS
  ChangeLog
  contrib/redhat/collectd.spec
  version-gen.sh
Labels: Unlisted Change

#3427 Update master with 5.11 changelog
  AUTHORS
  ChangeLog
  contrib/redhat/collectd.spec
  version-gen.sh
Labels: Unlisted Change

#3433 Fix memory leak in write_riemann
  src/write_riemann.c
Labels: Unlisted Change
