Repository collectd/collectd, pull requests merged in 2020-02, with the labels that each got.

#3339 Expose meta_data_toc function in utils_cache.
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
Labels: core

#3265 Allow cURL Statistics option in write-http plugin
  Makefile.am
  src/collectd.conf.pod
  src/write_http.c
Labels: Feature, Pending feedback

#3303 buddyinfo plugin: new plugin for memory fragmentation info
  AUTHORS
  Makefile.am
  README
  configure.ac
  src/buddyinfo.c
  src/collectd.conf.in
  src/collectd.conf.pod
  src/types.db
Labels: New plugin

#3273 dpdk_telemetry plugin: add plugin for DPDK metrics via DPDK Telemetry library
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/dpdk_telemetry.c
  src/types.db
Labels: New plugin

#3274 dcpmm plugin
  AUTHORS
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/dcpmm.c
  src/types.db
Labels: New plugin

#1034 Autoload matches and targets in the same way of plugins.
  src/daemon/filter_chain.c
Labels: Pending feedback

#3187 ipstats plugin: Count incoming, outgoing, forwarded packets (new plugin)
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/ipstats.c
Labels: New plugin

#3204 UBI plugin: collect some stats about the UBIFS
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/types.db
  src/ubi.c
Labels: New plugin

#3191 network plugin: Add a new metadata "network:ip_address"
  src/network.c
  src/network_test.c
Labels: Feature

#3162 write_influxdb_udp: new plugin to send values to InfluxDB using line protocol via udp.
  Makefile.am
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/write_influxdb_udp.c
Labels: New plugin

#2528 nut: add readout of power
  src/nut.c
Labels: Feature

#2635 Cleanup version-gen.sh
  version-gen.sh
Labels: Cleanup

#3380 Remove section about self-approve patches
  docs/maintainer_guide.md
Labels: Unlisted Change, documentation

#2926 New plugin: redfish
  Makefile.am
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/redfish.c
  src/redfish_test.c
Labels: New plugin

#3045 logparser: Utility for filtering and parsing log messages
  Makefile.am
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/logparser.c
  src/logparser_test.c
  src/tail.c
  src/tail_csv.c
  src/utils/message_parser/message_parser.c
  src/utils/message_parser/message_parser.h
  src/utils/message_parser/message_parser_test.c
  src/utils/tail/tail.c
  src/utils/tail/tail.h
  src/utils_tail_match.c
  src/utils_tail_match.h
Labels: New plugin

#3384 Forward-port and rebase of "New Capabilities plugin #3292"
  Makefile.am
  README
  configure.ac
  src/capabilities.c
  src/capabilities_test.c
  src/collectd.conf.in
  src/collectd.conf.pod
  src/utils/dmi/dmi.c
  src/utils/dmi/dmi.h
Labels: New plugin

#3363 exec plugin: replace select with poll
  src/exec.c
Labels: core

#3044 GenericJMX plugin: Support boolean input
  bindings/java/org/collectd/java/GenericJMXConfValue.java
Labels: Feature

#2991 Add 'quorum' stat to ZooKeeper plugin
  src/zookeeper.c
Labels: Feature
