Repository collectd/collectd, pull requests merged in 2020-04, with the labels that each got.

#3435 Fix memory leak in write_riemann
  src/write_riemann.c
Labels: Unlisted Change

#2841 New plugin to read RAID events
  Makefile.am
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/mdevents.c
  src/mdevents_test.c
Labels: New plugin, linux only

#3438 Merge 5.10 into 5.11
  AUTHORS
  src/write_riemann.c
Labels: Unlisted Change

#3410 amqp: allow multiple hosts for failover
  src/amqp.c
  src/collectd.conf.pod
Labels: Feature

#3445 Add varnish 6 support
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/varnish.c
Labels: Feature

#3450 Zookeeper - Add missing 3.5 mntr fields
  src/zookeeper.c
Labels: Feature
