Repository collectd/collectd, pull requests merged in 2020-09, with the labels that each got.

#3555 .cirrus.yml: Remove Debian Jessie.
  .cirrus.yml
Labels: Cleanup, Unlisted Change

#3558 libcollectdclient: Don't initialize a char with 0xF8.
  src/libcollectdclient/network_parse.c
Labels: Bug, solaris only

#3557 Remove the "ascent" plugin.
  Makefile.am
  README
  configure.ac
  src/ascent.c
  src/collectd.conf.in
  src/collectd.conf.pod
Labels: Cleanup

#3564 snmp_agent plugin: Fix strncat() truncation warning.
  src/snmp_agent.c
Labels: Bug

#3565 Update changelog and version number for release 5.12.
  ChangeLog
  version-gen.sh
Labels: Unlisted Change

#3566 Makefile.am: Link test_plugin_intel_rdt with libpqos.
  Makefile.am
Labels: build

#3567 Makefile.am: Add types.grpc.pb.{cc,h} to CLEANFILES.
  Makefile.am
Labels: build

#3551 Finalized formatting distribution metrics to JSON
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/metric_test.c
  src/utils/format_json/format_json.c
  src/utils/format_json/format_json_test.c
Labels: Interns

#3556 Remove the "XMMS" plugin.
  Makefile.am
  README
  configure.ac
  src/collectd.conf.in
  src/xmms.c
Labels: Automerge, Cleanup

#3571 write_influx_udp: build influxdb points outside de mutex.
  src/write_influxdb_udp.c
Labels: Feature

#3573 .cirrus.yml: Add Debian Buster.
  .cirrus.yml
Labels: Unlisted Change, build

#3579 Fix bug inside write_http plugin
  src/write_http.c
Labels: Bug

#3570 Utils cache: Start value
  src/daemon/distribution.c
  src/daemon/distribution.h
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
Labels: Interns

#3578 Fix memory leaks in write_http plugin
  src/write_http.c
Labels: Bug

#3582 Utils cache destroy
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/plugin.c
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
  src/daemon/utils_cache_test.c
Labels: Bug, Interns

#3559 daemon: Fix the build on Solaris.
  configure.ac
  solaris-ci.flags
  src/daemon/cmd.c
  src/daemon/collectd.c
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/metric_test.c
  src/daemon/plugin.c
  src/utils/common/common.c
  src/utils/common/common.h
  src/utils/format_graphite/format_graphite.c
  src/utils/format_json/format_json_test.c
  src/utils/format_stackdriver/format_stackdriver_test.c
  src/utils/message_parser/message_parser_test.c
  src/utils/strbuf/strbuf.c
Labels: Unlisted Change

#3586 Merge main into collectd-6.0
  .cirrus.yml
  .travis.yml
  AUTHORS
  ChangeLog
  Makefile.am
  README
  configure.ac
  contrib/collection3/etc/collection.conf
  contrib/curl_jolokia/curl_jolokia.conf
  contrib/curl_jolokia/jolokia_2_collectdcfg.py
  docs/BUILD.dpdkstat.md
  docs/CONTRIBUTING.md
  src/capabilities.c
  src/capabilities_test.c
  src/ceph.c
  src/collectd-snmp.pod
  src/collectd.conf.in
  src/collectd.conf.pod
  src/cpu.c
  src/curl.c
  src/curl_jolokia.c
  src/daemon/collectd.c
  src/entropy.c
  src/infiniband.c
  src/intel-nvme.h
  src/intel_pmu.c
  src/intel_rdt.c
  src/intel_rdt_test.c
  src/irq.c
  src/libcollectdclient/network_parse.c
  src/memory.c
  src/mysql.c
  src/netlink.c
  src/netlink_test.c
  src/netstat_udp.c
  src/network_test.c
  src/nfs.c
  src/nvme.h
  src/processes.c
  src/sensors.c
  src/slurm.c
  src/smart.c
  src/smart_test.c
  src/snmp.c
  src/snmp_agent.c
  src/swap.c
  src/types.db
  src/ubi.c
  src/utils/strbuf/strbuf.h
  src/write_influxdb_udp.c
  src/write_prometheus.c
  src/zookeeper.c
  version-gen.sh
Labels: Unlisted Change

#3760 configfile.c: Fix memory leaks in case of failure
  src/daemon/configfile.c
Labels: Bug, Interns
