Repository collectd/collectd, pull requests merged in 2023-11, with the labels that each got.

#4154 Intel RDT: fix compilation with libpqos < 4.4.
  src/intel_rdt.c
Labels: build

#4155 Add Valgrind suppression for libvirt memory leak.
  src/valgrind.suppress
Labels: Unlisted Change

#4156 curl_stats: fix compatibility with new versions of cURL.
  src/utils/curl_stats/curl_stats.c
Labels: build

#4157 Add new GitHub action for running `make distcheck`.
  .github/workflows/build.yml
  .github/workflows/distcheck.yml
Labels: Unlisted Change

#4158 Write MongoDB plugin: fix format trunction errors.
  src/write_mongodb.c
Labels: Unlisted Change

#4111 Fix compile warning for amqp
  configure.ac
  src/amqp.c
Labels: build, Cleanup, Unlisted Change

#4145 Update README.md
  README.md
Labels: Unlisted Change

#4162 Build workflow: remove old distros.
  .github/workflows/build.yml
Labels: Unlisted Change

#4163 Build workflow: Add Fedora 38 and 39.
  .github/workflows/build.yml
  .github/workflows/distcheck.yml
Labels: Unlisted Change

#4165 Netlink plugin: complete initialize structs used for testing.
  src/netlink_test.c
  src/smart.c
Labels: build, Unlisted Change

#4168 Workflow build: upload `config.log` and other log files.
  .github/workflows/build.yml
Labels: Unlisted Change

#4167 gmond plugin: Import `<ganglia.h>`.
  configure.ac
  src/gmond.c
Labels: build

#4170 Workflows: rename "sid_amd64" to "debian_unstable".
  .cirrus.yml
  .github/workflows/build.yml
Labels: Unlisted Change

#4164 Notify upstart/systemd after initialization is complete.
  src/daemon/cmd.c
  src/daemon/cmd.h
  src/daemon/collectd.c
Labels: linux only

#4171 Improve CI workflows
  .cirrus.yml
  .github/workflows/build.yml
  src/procevent.c
Labels: Unlisted Change
