Repository collectd/collectd, pull requests merged in 2023-12, with the labels that each got.

#4174 [collectd 6.0] Fix the build
  .cirrus.yml
  .github/workflows/build.yml
  .github/workflows/distcheck.yml
  configure.ac
  src/capabilities.c
  src/cpu.c
  src/gmond.c
  src/intel_rdt.c
  src/mdevents_test.c
  src/netlink_test.c
  src/nut.c
  src/procevent.c
  src/smart.c
  src/utils/curl_stats/curl_stats.c
  src/valgrind.suppress
Labels: Unlisted Change

#4179 write_log plugin: Remove empty lines, add example config
  src/collectd.conf.in
  src/collectd.conf.pod
  src/write_log.c
Labels: Bug, documentation

#4182 configure: Disable the write_http plugin if libyajl2 is not found.
  configure.ac
Labels: build, Unlisted Change

#4176 [collectd 6] add reference counting to plugins that register multiple callbacks with the same `user_data_t`.
  src/write_http.c
  src/write_riemann.c
  src/write_stackdriver.c
  src/write_syslog.c
  src/write_tsdb.c
Labels: Unlisted Change

#4196 [collectd 6] New utility: `resource_metrics` to group metrics by resource.
  Makefile.am
  src/daemon/metric.c
  src/daemon/metric.h
  src/utils/resource_metrics/resource_metrics.c
  src/utils/resource_metrics/resource_metrics.h
  src/utils/resource_metrics/resource_metrics_test.c
Labels: Unlisted Change

#4203 [collectd 6] gpu_sysman plugin: Fix double reporting of metric.
  src/gpu_sysman.c
Labels: Bug, Unlisted Change

#4201 [collectd 6] .github/workflows/build.yml: Remove Ubuntu Bionic.
  .github/workflows/build.yml
Labels: Unlisted Change

#4207 [collectd 6] Link more things into `libplugin_mock.la`.
  Makefile.am
Labels: build, Unlisted Change

#4205 cmds: Add a unittest for `cmd_parse_putval`.
  Makefile.am
  src/utils/cmds/putval.c
  src/utils/cmds/putval_test.c
  src/utils/common/common.c
  src/utils/common/common.h
  src/utils/common/common_test.c
Labels: Unlisted Change

#4206 [collectd 6] Write Prometheus plugin: Ensure metric and label names are properly formatted.
  Makefile.am
  configure.ac
  src/utils/strbuf/strbuf.c
  src/utils/strbuf/strbuf.h
  src/utils/strbuf/strbuf_test.c
  src/write_prometheus.c
  src/write_prometheus_test.c
Labels: Bug

#3840 collection3: fix inappropriate usage of CGI:param
  contrib/collection3/lib/Collectd/Graph/Common.pm
Labels: Unlisted Change

#4208 .cirrus.yml: Provide expected plugin list to `check-built-plugins.sh` if present.
  .cirrus.yml
  .expected-plugins/centos9
  .expected-plugins/debian10
  .expected-plugins/debian11
  .expected-plugins/debian12
  .expected-plugins/debian_unstable
  .expected-plugins/fedora38
  .expected-plugins/fedora39
  .expected-plugins/fedora_main
  .expected-plugins/ubuntu20.04
  .expected-plugins/ubuntu22.04
  .expected-plugins/ubuntu23.10
  .github/workflows/build.yml
  .github/workflows/distcheck.yml
Labels: Unlisted Change

#4214 [collectd 6] src/daemon/metric.c: Fix memory corruption in `label_set_delete`.
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/metric_test.c
Labels: Bug

#4022 EPICS plugin
  Makefile.am
  README.md
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/epics.c
Labels: New plugin
