Repository collectd/collectd, pull requests merged in 2024-02, with the labels that each got.

#4268 [collectd 6] format_stackdriver: When JSON generation fails, reset the generator …
  src/utils/format_stackdriver/format_stackdriver.c
Labels: Automerge, Fix

#4270 [collectd 6] format_stackdriver: Add proper error handling to `sd_output_reset()`.
  src/utils/format_stackdriver/format_stackdriver.c
  src/utils/format_stackdriver/format_stackdriver.h
  src/write_stackdriver.c
Labels: Automerge, Maintenance

#4269 format_stackdriver: When JSON generation fails, reset the generator b…
  src/utils/format_stackdriver/format_stackdriver.c
  src/utils/format_stackdriver/format_stackdriver.h
  src/write_stackdriver.c
Labels: Fix

#4266 [collectd 6] Introduce a floating point counter type.
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/plugin.h
  src/daemon/utils_cache.c
  src/daemon/utils_cache_test.c
  src/utils/cmds/cmds_test.c
  src/utils/cmds/putmetric.c
  src/utils/common/common.c
  src/utils/format_graphite/format_graphite.c
  src/utils/format_influxdb/format_influxdb.c
  src/utils/format_influxdb/format_influxdb.h
  src/utils/format_json/format_json.c
  src/utils/format_json/format_json_test.c
  src/utils/format_json/open_telemetry.c
  src/utils/format_kairosdb/format_kairosdb.c
  src/utils/format_open_telemetry/format_open_telemetry.cc
  src/utils/format_stackdriver/format_stackdriver.c
  src/utils/format_stackdriver/format_stackdriver_test.c
  src/utils/value_list/value_list.h
  src/write_http.c
  src/write_influxdb_udp.c
  src/write_prometheus.c
Labels: Feature, core

#4259 [collectd 6] ci: .cirrus.yml: Upload `.log` files as artifacts.
  .cirrus.yml
Labels: Automerge, Maintenance

#4247 interface plugin: Reorder implementations to put kstat above getifaddrs.
  src/interface.c
Labels: solaris only, Automerge, Fix

#4274 .cirrus.yml: Add task for Mac OS X, cleanup and improvements.
  .cirrus.yml
Labels: Maintenance

#4275 [collectd 6] memory plugin: Report the `system.linux.memory.available` metric.
  src/memory.c
Labels: Feature

#4278 [collectd 6] swap plugin: Add the `system.paging.faults` metric.
  src/swap.c
Labels: Feature

#4281 epics: Fix potential deadlock in handle_label_event
  src/epics.c
Labels: Fix

#4285 write_prometheus plugin: Fix a deadlock due to a leaked mutex.
  src/write_prometheus.c
Labels: Automerge, Fix

#4286 [collectd 6] Enable `-Wstrict-prototypes`.
  .cirrus.yml
  .github/workflows/build.yml
  configure.ac
  src/capabilities.c
  src/connectivity.c
  src/daemon/plugin.c
  src/daemon/utils_cache.c
  src/dpdkstat.c
  src/grpc.cc
  src/intel_rdt.c
  src/intel_rdt_test.c
  src/ipmi.c
  src/libcollectdclient/network_parse_test.c
  src/netlink.c
  src/network_test.c
  src/ovs_events.c
  src/ovs_stats.c
  src/procevent.c
  src/redfish_test.c
  src/sysevent.c
  src/utils/ovs/ovs.c
  src/utils/proc_pids/proc_pids_test.c
  src/utils/strbuf/strbuf.c
  src/virt.c
  src/write_influxdb_udp.c
  src/write_kafka.c
  src/write_prometheus.c
Labels: Maintenance

#4271 [collectd 6] New plugin (sort of): OpenTelemetry receiver
  Makefile.am
  configure.ac
  src/collectd.conf.in
  src/collectd.conf.pod
  src/daemon/utils_cache.c
  src/open_telemetry.cc
  src/open_telemetry.h
  src/open_telemetry_exporter.cc
  src/open_telemetry_receiver.cc
Labels: Feature, New plugin

#4223 [collectd 6] Use real collectd metric functions in gpu_sysman plugin tests
  Makefile.am
  src/gpu_sysman_test.c
Labels: Maintenance

#4279 memory.c: workaround to let ValuesPercentage works again without "available"
  src/memory.c
Labels: Feature

#4284 [collectd 6] write_prometheus plugin: Fix handling of multiple resources.
  Makefile.am
  src/write_prometheus.c
  src/write_prometheus_test.c
Labels: Fix

#4287 [collectd 6] Implement "UpDownCounter" metric types.
  src/cpu.c
  src/cpu_test.c
  src/daemon/metric.c
  src/daemon/metric.h
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
  src/daemon/utils_cache_test.c
  src/df.c
  src/disk.c
  src/memory.c
  src/open_telemetry_receiver.cc
  src/utils/cmds/putmetric.c
  src/utils/common/common.c
  src/utils/common/common.h
  src/utils/common/common_test.c
  src/utils/format_graphite/format_graphite.c
  src/utils/format_influxdb/format_influxdb.c
  src/utils/format_json/format_json.c
  src/utils/format_json/open_telemetry.c
  src/utils/format_kairosdb/format_kairosdb.c
  src/utils/format_open_telemetry/format_open_telemetry.cc
  src/utils/format_stackdriver/format_stackdriver.c
  src/utils/format_stackdriver/format_stackdriver_test.c
  src/utils/value_list/value_list.c
  src/utils/value_list/value_list.h
  src/write_prometheus.c
  src/write_prometheus_test.c
Labels: Feature

#4238 lua: add missing test case for #3779, #4235
  Makefile.am
  src/lua_test.c
Labels: Maintenance

#4273 [collectd 6] processes plugin: Migrate to collectd 6 data structures.
  configure.ac
  src/processes.c
Labels: Feature

#4288 ci: Trigger a website update after uploading a release artifact.
  .github/workflows/release.yml
Labels: Maintenance
