Repository collectd/collectd, pull requests merged in 2024-01, with the labels that each got.

#4232 write_riemann plugin: Terminate `riemann_event_set` arguments with `RIEMANN_EVENT_FIELD_NONE`.
  src/write_riemann.c
Labels: Bug, Automerge

#3795 [collectd 6] lua: migrate the Lua plugin to v6.0
  configure.ac
  src/collectd-lua.pod
  src/lua.c
  src/utils_lua.c
  src/utils_lua.h
Labels: Feature, Automerge

#4235 lua: add missing notification callback
  src/collectd-lua.pod
  src/lua.c
  src/utils_lua.c
Labels: Feature

#4233 [collectd 6] feat: Improve `sstrncpy` semantic.
  src/utils/common/common.c
  src/utils/common/common.h
  src/utils/common/common_test.c
Labels: Feature, Automerge

#4230 Import changes to `.github/workflows/` from the `collectd-6.0` branch.
  .cirrus.yml
  .github/workflows/build.yml
  .github/workflows/distcheck.yml
Labels: Automerge, Unlisted Change

#4228 [collectd 6] interface plugin: Align metrics with OpenTelemetry recommendations.
  src/interface.c
Labels: Feature, Automerge

#4224 [collectd 6] Memory plugin: Add "shared", drop "slab" and "available", report utilization as ratio.
  src/collectd.conf.in
  src/collectd.conf.pod
  src/memory.c
Labels: Feature, Automerge

#4236 [collectd 6] feat: Add the `--enable-compatibility-mode` flag to the `configure` script.
  .cirrus.yml
  .github/workflows/build.yml
  configure.ac
Labels: Feature

#4218 [collectd 6] df plugin: Align metrics with OpenTelemetry recommendations.
  src/collectd.conf.in
  src/collectd.conf.pod
  src/df.c
Labels: Feature, Automerge

#3917 Fix some gcc warnings with more strict checks
  src/cgroups.c
  src/conntrack.c
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
  src/infiniband.c
  src/libcollectdclient/network_parse.c
  src/logparser.c
  src/redfish.c
  src/statsd.c
  src/table.c
  src/threshold.c
  src/turbostat.c
  src/utils/format_json/format_json.c
  src/utils/format_stackdriver/format_stackdriver.c
  src/write_prometheus.c
  src/write_riemann_threshold.c
  src/write_syslog.c
  src/write_tsdb.c
Labels: Fix

#4244 [collectd 6] remove unused uc_get_history() from src/daemon/utils_cache.c
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
Labels: Unlisted Change

#4239 gpu_sysman: enable plugin automatically when `pkg-config` finds `level-zero` dependency
  Makefile.am
  configure.ac
Labels: Feature

#4234 docs: Document important labels and how to interact with them.
  docs/CONTRIBUTING.md
Labels: Maintenance

#4242 disk: add /proc/diskstats fields 15 to 20 in KERNEL_LINUX
  src/disk.c
  src/types.db
Labels: Feature

#4216 [collectd 6] cpu plugin: Align metrics with OpenTelemetry recommendations.
  Makefile.am
  src/collectd.conf.in
  src/collectd.conf.pod
  src/cpu.c
  src/cpu_test.c
Labels: Feature, Automerge

#4217 [collectd 6] disk plugin: Align metrics with OpenTelemetry recommendations.
  src/disk.c
Labels: Feature, Automerge

#4246 [collectd 6] docs: Fix the default value of the memory plugin's `ReportLimit` option.
  src/collectd.conf.pod
Labels: Maintenance

#4198 [collectd 6] Import plugin changes from `main`.
  src/bind.c
  src/collectd-nagios.c
  src/cpufreq.c
  src/hugepages.c
  src/intel_pmu.c
  src/mysql.c
  src/nginx.c
  src/ovs_stats.c
  src/processes.c
  src/smart_test.c
  src/swap.c
  src/ubi.c
  src/virt.c
  src/vmem.c
Labels: Maintenance

#4248 disk plugin: Build `disk_submit_single` on Linux only.
  src/disk.c
Labels: Maintenance

#4250 .cirrus.yml: statgrab: Print `ldd` of failing plugins. Continue on error.
  .cirrus.yml
Labels: Maintenance

#4251 [collectd 6] ci: Remove the "statgrab" task from CirrusCI.
  .cirrus.yml
Labels: Automerge, Maintenance

#4252 [collectd 6] fix: df plugin: Fix an array out of bounds crash.
  src/df.c
Labels: Automerge, Fix

#4256 disk.c: add config options to support diskstats 15-20 in KERNEL_LINUX
  src/collectd.conf.in
  src/collectd.conf.pod
  src/disk.c
Labels: Feature

#4190 [collectd 6] Swap plugin: Migrate to collectd 6 data structures.
  src/collectd.conf.in
  src/collectd.conf.pod
  src/swap.c
Labels: Feature, Automerge

#4243 [collectd 6] Fix most -Wpedantic warnings in collectd core
  .gitignore
  src/daemon/plugin.c
  src/daemon/utils_cache.c
  src/redfish.c
  src/utils/format_stackdriver/format_stackdriver.c
  src/utils/lookup/vl_lookup_test.c
  src/utils/resource_metrics/resource_metrics.c
  src/utils/utf8/utf8_test.c
  src/utils/value_list/value_list_test.c
  src/write_prometheus.c
Labels: Automerge, Maintenance

#4257 [collectd 6] fix: Handle metric families with zero metrics gracefully.
  src/chrony.c
  src/daemon/plugin.c
  src/df.c
  src/disk.c
  src/ipc.c
  src/irq.c
  src/ping.c
  src/utils/format_json/format_json_test.c
Labels: core, Automerge, Fix

#4260 write_redis plugin: Clean up allocated fields in `wr_config_free()`.
  src/write_redis.c
Labels: Automerge, Maintenance

#4261 [collectd 6]: Fix some GCC "-Wextra" warnings in collectd core
  src/daemon/plugin.c
  src/daemon/utils_cache.c
  src/utils/metadata/meta_data.c
Labels: Maintenance

#4262 [collectd 6, WIP] Fix more GCC "-Wpedantic" warnings
  src/dcpmm.c
  src/dpdk_telemetry.c
  src/dpdkevents.c
  src/dpdkstat.c
  src/intel_pmu.c
  src/ipmi.c
  src/mcelog.c
  src/mdevents.c
  src/utils/cmds/cmds_test.c
  src/utils/dpdk/dpdk.c
  src/utils/dpdk/dpdk.h
  src/utils/ovs/ovs.c
Labels: Maintenance

#4264 [collectd 6, WIP] Fix more GCC "-Wextra" warnings in collectd core
  src/utils/format_stackdriver/format_stackdriver.c
  src/utils/match/match.h
  src/utils/message_parser/message_parser.c
  src/utils/proc_pids/proc_pids.c
Labels: Maintenance

#4265 [collectd 6] cache: Provide the first metric value available alongside the first metric time.
  Makefile.am
  src/daemon/plugin.c
  src/daemon/utils_cache.c
  src/daemon/utils_cache.h
  src/daemon/utils_cache_test.c
  src/utils/format_stackdriver/format_stackdriver.c
  src/write_redis.c
  src/write_redis_test.c
Labels: Feature, core, Automerge
